resources:	
   - name: gitRes	
     type: GitRepo	
     configuration:	
       gitProvider: github_kirti	
       path: kirtisahu05/jfrogTest
pipelines: 
  - name: state_test
    steps:
      - name: testReport_u18
        type: Bash
        configuration:
          inputResources:
            - name: gitRes
        execution:
          onExecute:
            - pushd $res_gitResource_1_resourcePath
            - sudo chmod +x echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
            - ./echoTest.sh
      
      - name: run_file_restore
        type: Bash
        configuration:
          inputSteps:
            - name: testReport_u18
        execution:
          onExecute:
            - printenv
  - name: trigger_test
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          priority: 0
        execution:
          onExecute:
            - sleep 60
            - sleep 60
            - sleep 60
            - echo "done"
