resources:
  - name: gitrepo_res_jTest
    type: gitRepo
    repoPath: kirtisahu05/newTest
    configuration:
      integrationName: github_kirti
      branches:
        except: random
    initialVersion:
      sha: master

  - name: file_res_jTest
    type: file
    fileLocation: https://raw.githubusercontent.com/kirtisahu05/jfrogTest/master/pipelines.yml
    fileName: shippable.yml
    configuration:
      integrationName: github_kirti
    initialVersion:
      fileDtTm: random_value

  - name: image_res_jTest
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: docker_kirti
    initialVersion:
      imageTag: latest


  - name: webhookRes_jTest
    type: webhook
    configuration:
      integrationName: docker_kirti
    initialVersion:
      payload: "asd123"

  - name: clusterRes_jTest
    type: cluster
    configuration:
      integrationName: docker_kirti
      bastionHostIP: 1.2.3.4
      bastionUser: sshUser
      bastionIntegrationName: sshKeyIntegration
    initialVersion:
      targetCount: 1
      targetIP01: 1.2.3.4
      targetIP02: 1.2.3.4

pipelines:
  - name: jTest_pipeline
    setup:
      runtime: onHost
#       environmentVariables:
#         readOnly:
#           ENV1: value1
#           ENV2: value2  
    steps:
      - name: step_jTest
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          environmentVariables:
            normal:
              ENV1: value1
              ENV2: value2
              env3: value3
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - ver_1
        requires:
          integrations:
            - docker_kirti
          resources:
            - image_res_jTest
        triggeredBy:
          resources:
            - gitrepo_res_jTest
            - image_res_jTest
            - webhookRes_jTest
            - clusterRes_jTest
        execution:
          onExecute:
            - echo "executing..."
            - write_output file_res_jTest "fileDtTm"=$STEP_ID
        outputResources:
          - file_res_jTest
