resources:
  - name: gitrepo_res_jTest
    type: gitRepo
    repoPath: kirtisahu05/jfrogTest
    configuration:
      integrationName: github_kirti
      branches:
        except: random
    version:
      sha: master

  - name: file_res_jTest
    type: file
    fileLocation: https://raw.githubusercontent.com/kirtisahu05/jfrogTest/master/pipelines.yml
    fileName: shippable.yml
    configuration:
      integrationName: github_kirti
    version:
      fileDtTm: random_value

  - name: image_res_jTest
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: docker_kirti
    version:
      imageTag: latest

  - name: webhookRes_jTest
    type: webhook
    configuration:
      integrationName: github_kirti
    version:
      payload: "asd123"

  - name: clusterRes_jTest
    type: cluster
    configuration:
      integrationName: docker_kirti
      bastionHostIP: 1.2.3.4
      bastionUser: sshUser
      bastionIntegrationName: sshKeyIntegration

pipelines:
  - name: img_test_pipeline
    setup:
      runtime: onHost
    steps:
      - name: step_jTest
        type: bash
        configuration:
          affinityGroup: test_group
        requires:
          integrations:
            - docker_kirti
        triggeredBy:
          resources:
            - gitrepo_res_jTest
            - webhookRes_jTest
            - clusterRes_jTest
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          - file_res_jTest
          - image_res_jTest
      - name: img_test_push
        type: bash
        triggeredBy:
          steps:
            - step_jTest
        execution:
          onExecute:
            - printenv
            - write_output image_res_jTest "imageTag="$STEP_ID
        outputResources:
          - image_res_jTest
        requires:
          integrations:
            - github_kirti
      - name: img_read_Asdasdasdasdasdasdasdasdasdasdasdasdasdasd
        type: bash
        execution:
          onExecute:
            - printenv
        requires:
          resources:
            - image_res_jTest
#   - name: overlap_test
#     setup:
#       runtime: onHost
#     steps:
#       - name: over1 
#         type: bash
#         configuration:
#           affinityGroup: test_group
#         requires:
#           integrations:
#             - docker_kirti
#         triggeredBy:
#           resources:
#             - gitrepo_res_jTest
#             - webhookRes_jTest
#             - clusterRes_jTest
#         execution:
#           onExecute:
#             - echo "executing..."
#       - name: over2_1
#         type: bash
#         triggeredBy:
#           steps:
#             - over1
#         execution:
#           onExecute:
#             - printenv
#             - write_output image_res_jTest "imageTag="$STEP_ID
#         outputResources:
#           - image_res_jTest
#       - name: over2_3
#         type: bash
#         execution:
#           onExecute:
#             - printenv
#         triggeredBy:
#           steps:
#             - over1
#       - name: over2_4
#         type: bash
#         execution:
#           onExecute:
#             - printenv
#         triggeredBy:
#           steps:
#             - over1
#       - name: over2_5
#         type: bash
#         execution:
#           onExecute:
#             - printenv
#         triggeredBy:
#           steps:
#             - over1
#       - name: over2_2
#         type: bash
#         execution:
#           onExecute:
#             - printenv
#         requires:
#           resources:
#             - webhookRes_jTest
#         triggeredBy:
#           steps:
#             - over1
#       - name: over3_1
#         type: bash
#         execution:
#           onExecute:
#             - printenv
#         triggeredBy:
#           steps:
#             - over2_1
#       - name: over3_2
#         type: bash
#         execution:
#           onExecute:
#             - printenv
#         triggeredBy:
#           steps:
#             - over2_1
